name: spmd tests

on:
  push:
    branches:
    - main
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'

jobs:

  pytest_tests:
    runs-on: linux.12xlarge
    strategy:
      matrix:
        python-version: ["3.9"]
    container:
      image: python:${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f spmd/requirements_dev.txt ]; then pip install -r spmd/requirements_dev.txt; fi
          if [ -f spmd/requirements.txt ]; then pip install -r spmd/requirements.txt --find-links https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html; fi
      - name: Test with pytest
        run: |
          pytest --cov=spmd test/spmd/
